# https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action#testing-out-your-action-in-a-workflow
name: 'Run tests'
description: 'Run tests'
runs:
  using: 'docker'
  image: 'testing/Dockerfile'
  
  # TODO: add other tests
  entrypoint: 'python /github/workspace/testing/run-static.py'