on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests step
        uses: ./testing # Uses an action in the testing directory
        id: test